### Get all characters
GET http://localhost:3000/api/characters/

### Get character by id
GET http://localhost:3000/api/characters/GnderSY3e


### Post character
POST http://localhost:3000/api/characters/
Content-Type: application/json

{
    "name": "Test character 3",
    "status": "unknown",
    "species": "Human",
    "type": "Science experiment",
    "gender": "Male",
    "image": "https://rickandmortyapi.com/api/character/avatar/20.jpeg"
}


### Delete character by id
DELETE http://localhost:3000/api/characters/ZMteoCK_lxxIzAb9T0rDK

### Update character 
PUT http://localhost:3000/api/characters/p34MpnVHm77VYCWvOwZrb
Content-Type: application/json

{
    "id": "p34MpnVHm77VYCWvOwZrb",
    "name": "updated character333",
    "status": "unknown",
    "species": "Dog",
    "type": "Science experiment",
    "gender": "Male",
    "image": "https://rickandmortyapi.com/api/character/avatar/20.jpeg"
}